package net.thevpc.samples.petstore.core.actiongraph;

import java.util.ArrayList;
import java.util.List;

/**
 * Directed Acyclic Graph (DAG) of proposed facade calls generated by an AI agent.
 */
public class ActionGraph {
    private String id;
    private String goalDescription;
    private List<ActionNode> nodes = new ArrayList<>();

    public ActionGraph() {
    }

    public ActionGraph(String id, String goalDescription) {
        this.id = id;
        this.goalDescription = goalDescription;
    }

    public void addNode(ActionNode node) {
        nodes.add(node);
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getGoalDescription() {
        return goalDescription;
    }

    public void setGoalDescription(String goalDescription) {
        this.goalDescription = goalDescription;
    }

    public List<ActionNode> getNodes() {
        return nodes;
    }

    public void setNodes(List<ActionNode> nodes) {
        this.nodes = nodes;
    }
}
